/**
 * Commerce Platform API
 * RESTful API for the creation of Commerce Cases with Checkouts and the execution of Payments.
 *
 * OpenAPI spec version: 1.8.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Object containing billing address details
 */
export class Address {
  /**
   * Second line of street or additional address information such as apartments and suits
   */
  'additionalInfo'?: string;
  /**
   * City
   */
  'city'?: string;
  /**
   * ISO 3166-1 alpha-2 country code
   */
  'countryCode'?: string;
  /**
   * House number
   */
  'houseNumber'?: string;
  /**
   * State (ISO 3166-2 subdivisions), only if country=US, CA, CN, JP, MX, BR, AR, ID, TH, IN.
   */
  'state'?: string;
  /**
   * Street name
   */
  'street'?: string;
  /**
   * Zip code
   */
  'zip'?: string;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
    {
      name: 'additionalInfo',
      baseName: 'additionalInfo',
      type: 'string',
      format: '',
    },
    {
      name: 'city',
      baseName: 'city',
      type: 'string',
      format: '',
    },
    {
      name: 'countryCode',
      baseName: 'countryCode',
      type: 'string',
      format: '',
    },
    {
      name: 'houseNumber',
      baseName: 'houseNumber',
      type: 'string',
      format: '',
    },
    {
      name: 'state',
      baseName: 'state',
      type: 'string',
      format: '',
    },
    {
      name: 'street',
      baseName: 'street',
      type: 'string',
      format: '',
    },
    {
      name: 'zip',
      baseName: 'zip',
      type: 'string',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return Address.attributeTypeMap;
  }

  public constructor() {}
}
