/**
 * Commerce Platform API
 * RESTful API for the creation of Commerce Cases with Checkouts and the execution of Payments.
 *
 * OpenAPI spec version: 1.8.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Object containing billing address details
 */
export class Address {
  /**
   * Second line of street or additional address information such as apartments and suits
   */
  additionalInfo: string | null;
  /**
   * City
   */
  city: string | null;
  /**
   * ISO 3166-1 alpha-2 country code
   */
  countryCode: string | null;
  /**
   * House number
   */
  houseNumber: string | null;
  /**
   * State (ISO 3166-2 subdivisions), only if country=US, CA, CN, JP, MX, BR, AR, ID, TH, IN.
   */
  state: string | null;
  /**
   * Street name
   */
  street: string | null;
  /**
   * Zip code
   */
  zip: string | null;

  public constructor() {
    this.additionalInfo = null;
    this.city = null;
    this.countryCode = null;
    this.houseNumber = null;
    this.state = null;
    this.street = null;
    this.zip = null;
  }
}
