/**
 * Commerce Platform API
 * RESTful API for the creation of Commerce Cases with Checkouts and the execution of Payments.
 *
 * OpenAPI spec version: 1.8.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ApplePaymentDataTokenHeaderInformation } from './ApplePaymentDataTokenHeaderInformation.js';

/**
 * Additional information about the Apple payment data token. This information are needed for checking the validity of the payment data token before decryption.
 */
export class ApplePaymentDataTokenInformation {
  /**
   * Version information about the payment token. Currently only EC_v1 for ECC-encrypted data is supported.
   */
  'version'?: ApplePaymentDataTokenInformationVersionEnum;
  /**
   * Detached PKCS #7 signature, Base64 encoded as string. Signature of the payment and header data. The signature includes the signing certificate, its intermediate CA certificate, and information about the signing algorithm.
   */
  'signature'?: string;
  'header'?: ApplePaymentDataTokenHeaderInformation;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
    {
      name: 'version',
      baseName: 'version',
      type: 'ApplePaymentDataTokenInformationVersionEnum',
      format: '',
    },
    {
      name: 'signature',
      baseName: 'signature',
      type: 'string',
      format: '',
    },
    {
      name: 'header',
      baseName: 'header',
      type: 'ApplePaymentDataTokenHeaderInformation',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return ApplePaymentDataTokenInformation.attributeTypeMap;
  }

  public constructor() {}
}

export enum ApplePaymentDataTokenInformationVersionEnum {
  EcV1 = 'EC_V1',
}
