/**
 * Commerce Platform API
 * RESTful API for the creation of Commerce Cases with Checkouts and the execution of Payments.
 *
 * OpenAPI spec version: 1.8.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Additional information about the Apple payment data token header.
 */
export class ApplePaymentDataTokenHeaderInformation {
  /**
   * A hexadecimal Transaction identifier identifier as a string.
   */
  'transactionId'?: string;
  /**
   * SHA–256 hash, hex encoded as a string. Hash of the applicationData property of the original PKPaymentRequest object.
   */
  'applicationData'?: string;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
    {
      name: 'transactionId',
      baseName: 'transactionId',
      type: 'string',
      format: '',
    },
    {
      name: 'applicationData',
      baseName: 'applicationData',
      type: 'string',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return ApplePaymentDataTokenHeaderInformation.attributeTypeMap;
  }

  public constructor() {}
}
