/**
 * Commerce Platform API
 * RESTful API for the creation of Commerce Cases with Checkouts and the execution of Payments.
 *
 * OpenAPI spec version: 1.8.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Determines the type of the authorization that will be used. Allowed values:    * PRE_AUTHORIZATION - The payment creation results in a pre-authorization that is ready for Capture. Pre- authortizations can be reversed and can be captured within 30 days. The capture amount can be lower than the authorized amount.    * SALE - The payment creation results in an authorization that is already captured at the moment of approval.   If the parameter is not provided in the request, the default value will be PRE_AUTHORIZATION
 */
export enum AuthorizationMode {
  PreAuthorization = 'PRE_AUTHORIZATION',
  Sale = 'SALE',
}
