/**
 * Commerce Platform API
 * RESTful API for the creation of Commerce Cases with Checkouts and the execution of Payments.
 *
 * OpenAPI spec version: 1.8.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Object containing information about the end customer\'s bank account.
 */
export class BankAccountInformation {
  /**
   * IBAN of the end customer\'s bank account. The IBAN is the International Bank Account Number. It is an internationally agreed format for the BBAN and includes the ISO country code and two check digits.
   */
  'iban': string;
  /**
   * Account holder of the bank account with the given IBAN. Does not necessarily have to be the end customer (e.g. joint accounts).
   */
  'accountHolder': string;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
    {
      name: 'iban',
      baseName: 'iban',
      type: 'string',
      format: '',
    },
    {
      name: 'accountHolder',
      baseName: 'accountHolder',
      type: 'string',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return BankAccountInformation.attributeTypeMap;
  }

  public constructor() {}
}
