/**
 * Commerce Platform API
 * RESTful API for the creation of Commerce Cases with Checkouts and the execution of Payments.
 *
 * OpenAPI spec version: 1.8.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PaymentResponse } from '../models/PaymentResponse';

export class CancelPaymentResponse {
  'payment'?: PaymentResponse;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
    {
      name: 'payment',
      baseName: 'payment',
      type: 'PaymentResponse',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return CancelPaymentResponse.attributeTypeMap;
  }

  public constructor() {}
}
