/**
 * Commerce Platform API
 * RESTful API for the creation of Commerce Cases with Checkouts and the execution of Payments.
 *
 * OpenAPI spec version: 1.8.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CaptureOutput } from '../models/CaptureOutput';
import { PaymentStatusOutput } from '../models/PaymentStatusOutput';
import { StatusValue } from '../models/StatusValue';

export class CapturePaymentResponse {
  'captureOutput'?: CaptureOutput;
  'status'?: StatusValue;
  'statusOutput'?: PaymentStatusOutput;
  /**
   * Unique payment transaction identifier of the payment gateway.
   */
  'id'?: string;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
    {
      name: 'captureOutput',
      baseName: 'captureOutput',
      type: 'CaptureOutput',
      format: '',
    },
    {
      name: 'status',
      baseName: 'status',
      type: 'StatusValue',
      format: '',
    },
    {
      name: 'statusOutput',
      baseName: 'statusOutput',
      type: 'PaymentStatusOutput',
      format: '',
    },
    {
      name: 'id',
      baseName: 'id',
      type: 'string',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return CapturePaymentResponse.attributeTypeMap;
  }

  public constructor() {}
}
