/**
 * Commerce Platform API
 * RESTful API for the creation of Commerce Cases with Checkouts and the execution of Payments.
 *
 * OpenAPI spec version: 1.8.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CancellationReason } from './CancellationReason.js';
import { DeliveryInformation } from './DeliveryInformation.js';
import { PaymentReferences } from './PaymentReferences.js';

/**
 * If the shopping cart is specified, a Capture is made with the amount of the shopping cart for the items that are specified.
 */
export class CapturePaymentRequest {
  /**
   * Here you can specify the amount that you want to capture (specified in cents, where single digit currencies are presumed to have 2 digits). The amount can be lower than the amount that was authorized, but not higher.   If left empty, the full amount will be captured and the request will be final.   If the full amount is captured, the request will also be final.
   */
  'amount'?: number;
  /**
   * This property indicates whether this will be the final operation.  If the full amount should not captured but the property is set to true, the remaining amount will automatically be cancelled.
   */
  'isFinal'?: boolean;
  'cancellationReason'?: CancellationReason;
  'references'?: PaymentReferences;
  'delivery'?: DeliveryInformation;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
    {
      name: 'amount',
      baseName: 'amount',
      type: 'number',
      format: 'int64',
    },
    {
      name: 'isFinal',
      baseName: 'isFinal',
      type: 'boolean',
      format: '',
    },
    {
      name: 'cancellationReason',
      baseName: 'cancellationReason',
      type: 'CancellationReason',
      format: '',
    },
    {
      name: 'references',
      baseName: 'references',
      type: 'PaymentReferences',
      format: '',
    },
    {
      name: 'delivery',
      baseName: 'delivery',
      type: 'DeliveryInformation',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return CapturePaymentRequest.attributeTypeMap;
  }

  public constructor() {}
}
