/**
 * Commerce Platform API
 * RESTful API for the creation of Commerce Cases with Checkouts and the execution of Payments.
 *
 * OpenAPI spec version: 1.8.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CardFraudResults } from '../models/CardFraudResults';
import { ThreeDSecureResults } from '../models/ThreeDSecureResults';

/**
 * Object containing the card payment method details.
 */
export class CardPaymentMethodSpecificOutput {
  /**
   * Payment product identifier - please check product documentation for a full overview of possible values.
   */
  'paymentProductId'?: number;
  /**
   * Card Authorization code as returned by the acquirer
   */
  'authorisationCode'?: string;
  'fraudResults'?: CardFraudResults;
  'threeDSecureResults'?: ThreeDSecureResults;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
    {
      name: 'paymentProductId',
      baseName: 'paymentProductId',
      type: 'number',
      format: 'int32',
    },
    {
      name: 'authorisationCode',
      baseName: 'authorisationCode',
      type: 'string',
      format: '',
    },
    {
      name: 'fraudResults',
      baseName: 'fraudResults',
      type: 'CardFraudResults',
      format: '',
    },
    {
      name: 'threeDSecureResults',
      baseName: 'threeDSecureResults',
      type: 'ThreeDSecureResults',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return CardPaymentMethodSpecificOutput.attributeTypeMap;
  }

  public constructor() {}
}
