/**
 * Commerce Platform API
 * RESTful API for the creation of Commerce Cases with Checkouts and the execution of Payments.
 *
 * OpenAPI spec version: 1.8.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Information for card payments realized at a POS.
 */
export class CardPaymentDetails {
  /**
   * Reference to the card of the transaction.
   */
  'maskedCardNumber'?: string;
  /**
   * ID of the token. This property is populated when the payment was done with a token.
   */
  'paymentProcessingToken'?: string;
  /**
   * Token to identify the card in the reporting.
   */
  'reportingToken'?: string;
  /**
   * Identifier for a successful authorization, reversal or refund. Usually provided by the issuer system. Only provided for card payments.
   */
  'cardAuthorizationId'?: string;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
    {
      name: 'maskedCardNumber',
      baseName: 'maskedCardNumber',
      type: 'string',
      format: '',
    },
    {
      name: 'paymentProcessingToken',
      baseName: 'paymentProcessingToken',
      type: 'string',
      format: '',
    },
    {
      name: 'reportingToken',
      baseName: 'reportingToken',
      type: 'string',
      format: '',
    },
    {
      name: 'cardAuthorizationId',
      baseName: 'cardAuthorizationId',
      type: 'string',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return CardPaymentDetails.attributeTypeMap;
  }

  public constructor() {}
}
