/**
 * Commerce Platform API
 * RESTful API for the creation of Commerce Cases with Checkouts and the execution of Payments.
 *
 * OpenAPI spec version: 1.8.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AuthorizationMode } from './AuthorizationMode.js';
import { CardInfo } from './CardInfo.js';
import { CardRecurrenceDetails } from './CardRecurrenceDetails.js';
import { TransactionChannel } from './TransactionChannel.js';
import { UnscheduledCardOnFileRequestor } from './UnscheduledCardOnFileRequestor.js';
import { UnscheduledCardOnFileSequenceIndicator } from './UnscheduledCardOnFileSequenceIndicator.js';

/**
 * Object containing the specific input details for card payments.
 */
export class CardPaymentMethodSpecificInput {
  'authorizationMode'?: AuthorizationMode;
  'recurring'?: CardRecurrenceDetails;
  /**
   * ID of the token to use to create the payment.
   */
  'paymentProcessingToken'?: string;
  /**
   * Token to identify the card in the reporting.
   */
  'reportingToken'?: string;
  'transactionChannel'?: TransactionChannel;
  'unscheduledCardOnFileRequestor'?: UnscheduledCardOnFileRequestor;
  'unscheduledCardOnFileSequenceIndicator'?: UnscheduledCardOnFileSequenceIndicator;
  /**
   * Payment product identifier - please check product documentation for a full overview of possible values.
   */
  'paymentProductId'?: number;
  'card'?: CardInfo;
  /**
   * The URL that the customer is redirect to after the payment flow has finished. You can add any number of key value pairs in the query string that, for instance help you to identify the customer when they return to your site. Please note that we will also append some additional key value pairs that will also help you with this identification process. Note: The provided URL should be absolute and contain the protocol to use, e.g. http:// or https://. For use on mobile devices a custom protocol can be used in the form of protocol://. This protocol must be registered on the device first. URLs without a protocol will be rejected.
   */
  'returnUrl'?: string;
  /**
   * Period of payment occurrence for recurring and installment payments. Allowed values: * Yearly * Quarterly * Monthly  * Weekly * Daily Supported soon
   */
  'cardOnFileRecurringFrequency'?: CardPaymentMethodSpecificInputCardOnFileRecurringFrequencyEnum;
  /**
   * The end date of the last scheduled payment in a series of transactions. Format YYYYMMDD Supported soon
   */
  'cardOnFileRecurringExpiration'?: string;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
    {
      name: 'authorizationMode',
      baseName: 'authorizationMode',
      type: 'AuthorizationMode',
      format: '',
    },
    {
      name: 'recurring',
      baseName: 'recurring',
      type: 'CardRecurrenceDetails',
      format: '',
    },
    {
      name: 'paymentProcessingToken',
      baseName: 'paymentProcessingToken',
      type: 'string',
      format: '',
    },
    {
      name: 'reportingToken',
      baseName: 'reportingToken',
      type: 'string',
      format: '',
    },
    {
      name: 'transactionChannel',
      baseName: 'transactionChannel',
      type: 'TransactionChannel',
      format: '',
    },
    {
      name: 'unscheduledCardOnFileRequestor',
      baseName: 'unscheduledCardOnFileRequestor',
      type: 'UnscheduledCardOnFileRequestor',
      format: '',
    },
    {
      name: 'unscheduledCardOnFileSequenceIndicator',
      baseName: 'unscheduledCardOnFileSequenceIndicator',
      type: 'UnscheduledCardOnFileSequenceIndicator',
      format: '',
    },
    {
      name: 'paymentProductId',
      baseName: 'paymentProductId',
      type: 'number',
      format: 'int32',
    },
    {
      name: 'card',
      baseName: 'card',
      type: 'CardInfo',
      format: '',
    },
    {
      name: 'returnUrl',
      baseName: 'returnUrl',
      type: 'string',
      format: '',
    },
    {
      name: 'cardOnFileRecurringFrequency',
      baseName: 'cardOnFileRecurringFrequency',
      type: 'CardPaymentMethodSpecificInputCardOnFileRecurringFrequencyEnum',
      format: '',
    },
    {
      name: 'cardOnFileRecurringExpiration',
      baseName: 'cardOnFileRecurringExpiration',
      type: 'string',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return CardPaymentMethodSpecificInput.attributeTypeMap;
  }

  public constructor() {}
}

export enum CardPaymentMethodSpecificInputCardOnFileRecurringFrequencyEnum {
  Yearly = 'Yearly',
  Quarterly = 'Quarterly',
  Monthly = 'Monthly',
  Weekly = 'Weekly',
  Daily = 'Daily',
}
