/**
 * Commerce Platform API
 * RESTful API for the creation of Commerce Cases with Checkouts and the execution of Payments.
 *
 * OpenAPI spec version: 1.8.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Object containing additional non PCI DSS relevant card information. used instead of card (missing fields: cardNumber, expiryDate, cvv)
 */
export class CardInfo {
  /**
   * The card holder\'s name on the card.
   */
  'cardholderName'?: string;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
    {
      name: 'cardholderName',
      baseName: 'cardholderName',
      type: 'string',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return CardInfo.attributeTypeMap;
  }

  public constructor() {}
}
