/**
 * Commerce Platform API
 * RESTful API for the creation of Commerce Cases with Checkouts and the execution of Payments.
 *
 * OpenAPI spec version: 1.8.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Object containing data related to recurring.
 */
export class CardRecurrenceDetails {
  /**
   * * first = This transaction is the first of a series of recurring transactions * recurring = This transaction is a subsequent transaction in a series of recurring transactions  Note: For any first of a recurring the system will automatically create a token as you will need to use a token for any subsequent recurring transactions. In case a token already exists this is indicated in the response with a value of False for the isNewToken property in the response.
   */
  'recurringPaymentSequenceIndicator'?: string;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
    {
      name: 'recurringPaymentSequenceIndicator',
      baseName: 'recurringPaymentSequenceIndicator',
      type: 'string',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return CardRecurrenceDetails.attributeTypeMap;
  }

  public constructor() {}
}
