/**
 * Commerce Platform API
 * RESTful API for the creation of Commerce Cases with Checkouts and the execution of Payments.
 *
 * OpenAPI spec version: 1.8.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Object containing the line items of the invoice or shopping cart.
 */
export class CartItemInvoiceData {
  /**
   * Shopping cart item description. The description will also be displayed in the portal as the product name.
   */
  'description'?: string;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
    {
      name: 'description',
      baseName: 'description',
      type: 'string',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return CartItemInvoiceData.attributeTypeMap;
  }

  public constructor() {}
}
