/**
 * Commerce Platform API
 * RESTful API for the creation of Commerce Cases with Checkouts and the execution of Payments.
 *
 * OpenAPI spec version: 1.8.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CartItemInvoiceData } from './CartItemInvoiceData.js';
import { OrderLineDetailsPatch } from './OrderLineDetailsPatch.js';

/**
 * This object contains information of all items in the cart. If a cart item is provided, the productPrice and quantity is required.
 */
export class CartItemPatch {
  'invoiceData'?: CartItemInvoiceData;
  'orderLineDetails'?: OrderLineDetailsPatch;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
    {
      name: 'invoiceData',
      baseName: 'invoiceData',
      type: 'CartItemInvoiceData',
      format: '',
    },
    {
      name: 'orderLineDetails',
      baseName: 'orderLineDetails',
      type: 'OrderLineDetailsPatch',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return CartItemPatch.attributeTypeMap;
  }

  public constructor() {}
}
