/**
 * Commerce Platform API
 * RESTful API for the creation of Commerce Cases with Checkouts and the execution of Payments.
 *
 * OpenAPI spec version: 1.8.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CartItemStatus } from './CartItemStatus';

/**
 * Detailed information regarding an occurred payment event.
 */
export class CartItemOrderStatus {
  'cartItemStatus'?: CartItemStatus;
  /**
   * Amount of units for which this status is applicable, should be greater than zero
   */
  'quantity'?: number;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
    {
      name: 'cartItemStatus',
      baseName: 'cartItemStatus',
      type: 'CartItemStatus',
      format: '',
    },
    {
      name: 'quantity',
      baseName: 'quantity',
      type: 'number',
      format: 'int64',
    },
  ];

  static getAttributeTypeMap() {
    return CartItemOrderStatus.attributeTypeMap;
  }

  public constructor() {}
}
