/**
 * Commerce Platform API
 * RESTful API for the creation of Commerce Cases with Checkouts and the execution of Payments.
 *
 * OpenAPI spec version: 1.8.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AllowedPaymentActions } from './AllowedPaymentActions.js';
import { AmountOfMoney } from './AmountOfMoney.js';
import { CheckoutReferences } from './CheckoutReferences.js';
import { PaymentExecution } from './PaymentExecution.js';
import { PaymentInformationResponse } from './PaymentInformationResponse.js';
import { Shipping } from './Shipping.js';
import { ShoppingCartResult } from './ShoppingCartResult.js';
import { StatusCheckout } from './StatusCheckout.js';
import { StatusOutput } from './StatusOutput.js';

/**
 * The Checkout corresponds to the order of the WL API. We do not take additionalInput from the WL API. We have no  shipping and use deliveryAddress instead of address.
 */
export class CheckoutResponse {
  /**
   * reference to the Commerce Case.
   */
  commerceCaseId: string | null;
  /**
   * reference to the Checkout.
   */
  checkoutId: string | null;
  /**
   * Unique identifier for the customer.
   */
  merchantCustomerId: string | null;
  amountOfMoney: AmountOfMoney | null;
  references: CheckoutReferences | null;
  shipping: Shipping | null;
  shoppingCart: ShoppingCartResult | null;
  paymentExecutions: Array<PaymentExecution> | null;
  checkoutStatus: StatusCheckout | null;
  statusOutput: StatusOutput | null;
  paymentInformation: Array<PaymentInformationResponse> | null;
  /**
   * Creation date and time of the Checkout in RFC3339 format. It can either be provided in the request or otherwise will be automatically set to the time when the request CreateCommerceCase was received. Response values will always be in UTC time, but when providing this field in the requests, the time offset can have different formats.  Accepted formats are: * YYYY-MM-DD\'T\'HH:mm:ss\'Z\' * YYYY-MM-DD\'T\'HH:mm:ss+XX:XX * YYYY-MM-DD\'T\'HH:mm:ss-XX:XX * YYYY-MM-DD\'T\'HH:mm\'Z\' * YYYY-MM-DD\'T\'HH:mm+XX:XX * YYYY-MM-DD\'T\'HH:mm-XX:XX  All other formats may be ignored by the system.
   */
  creationDateTime: Date | null;
  allowedPaymentActions: Array<AllowedPaymentActions> | null;

  constructor() {
    this.commerceCaseId = null;
    this.checkoutId = null;
    this.merchantCustomerId = null;
    this.amountOfMoney = null;
    this.references = null;
    this.shipping = null;
    this.shoppingCart = null;
    this.paymentExecutions = null;
    this.checkoutStatus = null;
    this.statusOutput = null;
    this.paymentInformation = null;
    this.creationDateTime = null;
    this.allowedPaymentActions = null;
  }
}
