/**
 * Commerce Platform API
 * RESTful API for the creation of Commerce Cases with Checkouts and the execution of Payments.
 *
 * OpenAPI spec version: 1.8.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Object containing all details that are linked to the Checkout.
 */
export class CheckoutReferences {
  /**
   * Unique reference of the Checkout that is also returned for reporting and reconciliation purposes.
   */
  'merchantReference'?: string;
  /**
   * Optional parameter to define the shop or touchpoint where a sale has been realized (e.g. different stores).
   */
  'merchantShopReference'?: string;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
    {
      name: 'merchantReference',
      baseName: 'merchantReference',
      type: 'string',
      format: '',
    },
    {
      name: 'merchantShopReference',
      baseName: 'merchantShopReference',
      type: 'string',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return CheckoutReferences.attributeTypeMap;
  }

  public constructor() {}
}
