/**
 * Commerce Platform API
 * RESTful API for the creation of Commerce Cases with Checkouts and the execution of Payments.
 *
 * OpenAPI spec version: 1.8.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CheckoutResponse } from './CheckoutResponse.js';

/**
 * Object that holds the number of found Checkouts and the requested page of Checkouts
 */
export class CheckoutsResponse {
  /**
   * Number of found Checkouts
   */
  'numberOfCheckouts'?: number;
  /**
   * List of Checkouts
   */
  'checkouts'?: Array<CheckoutResponse>;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
    {
      name: 'numberOfCheckouts',
      baseName: 'numberOfCheckouts',
      type: 'number',
      format: 'int64',
    },
    {
      name: 'checkouts',
      baseName: 'checkouts',
      type: 'Array<CheckoutResponse>',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return CheckoutsResponse.attributeTypeMap;
  }

  public constructor() {}
}
