/**
 * Commerce Platform API
 * RESTful API for the creation of Commerce Cases with Checkouts and the execution of Payments.
 *
 * OpenAPI spec version: 1.8.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MerchantAction } from '../models/MerchantAction';
import { PaymentCreationOutput } from '../models/PaymentCreationOutput';
import { PaymentResponse } from '../models/PaymentResponse';

export class CompletePaymentResponse {
  'creationOutput'?: PaymentCreationOutput;
  'merchantAction'?: MerchantAction;
  'payment'?: PaymentResponse;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
    {
      name: 'creationOutput',
      baseName: 'creationOutput',
      type: 'PaymentCreationOutput',
      format: '',
    },
    {
      name: 'merchantAction',
      baseName: 'merchantAction',
      type: 'MerchantAction',
      format: '',
    },
    {
      name: 'payment',
      baseName: 'payment',
      type: 'PaymentResponse',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return CompletePaymentResponse.attributeTypeMap;
  }

  public constructor() {}
}
