/**
 * Commerce Platform API
 * RESTful API for the creation of Commerce Cases with Checkouts and the execution of Payments.
 *
 * OpenAPI spec version: 1.8.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CompleteFinancingPaymentMethodSpecificInput } from '../models/CompleteFinancingPaymentMethodSpecificInput';
import { CustomerDevice } from '../models/CustomerDevice';
import { Order } from '../models/Order';

/**
 * The Complete request is the last step to finalize the initially created Payment. It requires the completeFinancingPaymentMethodSpecificInput. The data for the order object should not differ from the previously provided information in Commerce Case, Checkout and Payment, but will not be validated nor automatically loaded from the Commerce Platform.
 */
export class CompletePaymentRequest {
  'financingPaymentMethodSpecificInput'?: CompleteFinancingPaymentMethodSpecificInput;
  'order'?: Order;
  'device'?: CustomerDevice;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
    {
      name: 'financingPaymentMethodSpecificInput',
      baseName: 'financingPaymentMethodSpecificInput',
      type: 'CompleteFinancingPaymentMethodSpecificInput',
      format: '',
    },
    {
      name: 'order',
      baseName: 'order',
      type: 'Order',
      format: '',
    },
    {
      name: 'device',
      baseName: 'device',
      type: 'CustomerDevice',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return CompletePaymentRequest.attributeTypeMap;
  }

  public constructor() {}
}
