/**
 * Commerce Platform API
 * RESTful API for the creation of Commerce Cases with Checkouts and the execution of Payments.
 *
 * OpenAPI spec version: 1.8.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Object containing contact details like email address and phone number.
 */
export class ContactDetails {
  /**
   * Email address of the customer
   */
  'emailAddress'?: string;
  /**
   * Phone number of the customer
   */
  'phoneNumber'?: string;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
    {
      name: 'emailAddress',
      baseName: 'emailAddress',
      type: 'string',
      format: '',
    },
    {
      name: 'phoneNumber',
      baseName: 'phoneNumber',
      type: 'string',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return ContactDetails.attributeTypeMap;
  }

  public constructor() {}
}
