/**
 * Commerce Platform API
 * RESTful API for the creation of Commerce Cases with Checkouts and the execution of Payments.
 *
 * OpenAPI spec version: 1.8.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AllowedPaymentActions } from './AllowedPaymentActions.js';
import { AmountOfMoney } from './AmountOfMoney.js';
import { CheckoutReferences } from './CheckoutReferences.js';
import { CreatePaymentResponse } from './CreatePaymentResponse.js';
import { ErrorResponse } from './ErrorResponse.js';
import { PaymentExecution } from './PaymentExecution.js';
import { Shipping } from './Shipping.js';
import { ShoppingCartResult } from './ShoppingCartResult.js';
import { StatusCheckout } from './StatusCheckout.js';
import { StatusOutput } from './StatusOutput.js';

/**
 * Object containing the reference of the Checkout for following requests.
 */
export class CreateCheckoutResponse {
  /**
   * Reference to the Checkout. Can be used for following requests to get and update the Checkout and execute the payment.
   */
  'checkoutId'?: string;
  'shoppingCart'?: ShoppingCartResult;
  'paymentResponse'?: CreatePaymentResponse;
  'errorResponse'?: ErrorResponse;
  'amountOfMoney'?: AmountOfMoney;
  'references'?: CheckoutReferences;
  'shipping'?: Shipping;
  'paymentExecution'?: PaymentExecution;
  'checkoutStatus'?: StatusCheckout;
  'statusOutput'?: StatusOutput;
  /**
   * Creation date and time of the Checkout in RFC3339 format. It can either be provided in the request or otherwise will be automatically set to the time when the request CreateCommerceCase was received. Response values will always be in UTC time, but when providing this field in the requests, the time offset can have different formats.  Accepted formats are: * YYYY-MM-DD\'T\'HH:mm:ss\'Z\' * YYYY-MM-DD\'T\'HH:mm:ss+XX:XX * YYYY-MM-DD\'T\'HH:mm:ss-XX:XX * YYYY-MM-DD\'T\'HH:mm\'Z\' * YYYY-MM-DD\'T\'HH:mm+XX:XX * YYYY-MM-DD\'T\'HH:mm-XX:XX  All other formats may be ignored by the system.
   */
  'creationDateTime'?: Date;
  'allowedPaymentActions'?: Array<AllowedPaymentActions>;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
    {
      name: 'checkoutId',
      baseName: 'checkoutId',
      type: 'string',
      format: 'UUID',
    },
    {
      name: 'shoppingCart',
      baseName: 'shoppingCart',
      type: 'ShoppingCartResult',
      format: '',
    },
    {
      name: 'paymentResponse',
      baseName: 'paymentResponse',
      type: 'CreatePaymentResponse',
      format: '',
    },
    {
      name: 'errorResponse',
      baseName: 'errorResponse',
      type: 'ErrorResponse',
      format: '',
    },
    {
      name: 'amountOfMoney',
      baseName: 'amountOfMoney',
      type: 'AmountOfMoney',
      format: '',
    },
    {
      name: 'references',
      baseName: 'references',
      type: 'CheckoutReferences',
      format: '',
    },
    {
      name: 'shipping',
      baseName: 'shipping',
      type: 'Shipping',
      format: '',
    },
    {
      name: 'paymentExecution',
      baseName: 'paymentExecution',
      type: 'PaymentExecution',
      format: '',
    },
    {
      name: 'checkoutStatus',
      baseName: 'checkoutStatus',
      type: 'StatusCheckout',
      format: '',
    },
    {
      name: 'statusOutput',
      baseName: 'statusOutput',
      type: 'StatusOutput',
      format: '',
    },
    {
      name: 'creationDateTime',
      baseName: 'creationDateTime',
      type: 'Date',
      format: 'date-time',
    },
    {
      name: 'allowedPaymentActions',
      baseName: 'allowedPaymentActions',
      type: 'Array<AllowedPaymentActions>',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return CreateCheckoutResponse.attributeTypeMap;
  }

  public constructor() {}
}
