/**
 * Commerce Platform API
 * RESTful API for the creation of Commerce Cases with Checkouts and the execution of Payments.
 *
 * OpenAPI spec version: 1.8.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AmountOfMoney } from '../models/AmountOfMoney';
import { CheckoutReferences } from '../models/CheckoutReferences';
import { OrderRequest } from '../models/OrderRequest';
import { Shipping } from '../models/Shipping';
import { ShoppingCartInput } from '../models/ShoppingCartInput';

/**
 * Request to create a Checkout for a Commerce Case. The payment for the Checkout can be directly executed if autoExecuteOrder = true. In this case, the paymentMethodSpecificInput must be provided and only a full order is possible.  If no amountOfMoney is provided, the platform will calculate the respective Checkout amount based on the cartItem productPrice and quantity.  In case of a payment error, the payment can be retried by providing the respective commerceCaseId and checkoutId to the the Order or Payment Execution endpoint.
 */
export class CreateCheckoutRequest {
  'amountOfMoney'?: AmountOfMoney;
  'references'?: CheckoutReferences;
  'shipping'?: Shipping;
  'shoppingCart'?: ShoppingCartInput;
  'orderRequest'?: OrderRequest;
  /**
   * Creation date and time of the Checkout in RFC3339 format. It can either be provided in the request or otherwise will be automatically set to the time when the request CreateCommerceCase was received. Response values will always be in UTC time, but when providing this field in the requests, the time offset can have different formats.  Accepted formats are: * YYYY-MM-DD\'T\'HH:mm:ss\'Z\' * YYYY-MM-DD\'T\'HH:mm:ss+XX:XX * YYYY-MM-DD\'T\'HH:mm:ss-XX:XX * YYYY-MM-DD\'T\'HH:mm\'Z\' * YYYY-MM-DD\'T\'HH:mm+XX:XX * YYYY-MM-DD\'T\'HH:mm-XX:XX  All other formats may be ignored by the system.
   */
  'creationDateTime'?: Date;
  /**
   * Set this flag to directly execute a payment when creating a Commerce Case or Checkout. If the value for autoExecuteOrder is set to true, the paymentMethodSpecificInput for the order is mandatory and has to be provided. The autoExecuteOrder can only be used for orderType = full. If no shoppingCart information has been provided, a Payment Execution will be created instead of an Order. As a consequence, only Payment Execution endpoints can be used.
   */
  'autoExecuteOrder'?: boolean;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
    {
      name: 'amountOfMoney',
      baseName: 'amountOfMoney',
      type: 'AmountOfMoney',
      format: '',
    },
    {
      name: 'references',
      baseName: 'references',
      type: 'CheckoutReferences',
      format: '',
    },
    {
      name: 'shipping',
      baseName: 'shipping',
      type: 'Shipping',
      format: '',
    },
    {
      name: 'shoppingCart',
      baseName: 'shoppingCart',
      type: 'ShoppingCartInput',
      format: '',
    },
    {
      name: 'orderRequest',
      baseName: 'orderRequest',
      type: 'OrderRequest',
      format: '',
    },
    {
      name: 'creationDateTime',
      baseName: 'creationDateTime',
      type: 'Date',
      format: 'date-time',
    },
    {
      name: 'autoExecuteOrder',
      baseName: 'autoExecuteOrder',
      type: 'boolean',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return CreateCheckoutRequest.attributeTypeMap;
  }

  public constructor() {}
}
