/**
 * Commerce Platform API
 * RESTful API for the creation of Commerce Cases with Checkouts and the execution of Payments.
 *
 * OpenAPI spec version: 1.8.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MerchantAction } from './MerchantAction.js';
import { PaymentCreationOutput } from './PaymentCreationOutput.js';
import { PaymentResponse } from './PaymentResponse.js';

/**
 * Object containing details on the created payment it has directly be executed.
 */
export class CreatePaymentResponse {
  'creationOutput'?: PaymentCreationOutput;
  'merchantAction'?: MerchantAction;
  'payment'?: PaymentResponse;
  /**
   * reference to the paymentExecution.
   */
  'paymentExecutionId'?: string;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
    {
      name: 'creationOutput',
      baseName: 'creationOutput',
      type: 'PaymentCreationOutput',
      format: '',
    },
    {
      name: 'merchantAction',
      baseName: 'merchantAction',
      type: 'MerchantAction',
      format: '',
    },
    {
      name: 'payment',
      baseName: 'payment',
      type: 'PaymentResponse',
      format: '',
    },
    {
      name: 'paymentExecutionId',
      baseName: 'paymentExecutionId',
      type: 'string',
      format: 'UUID',
    },
  ];

  static getAttributeTypeMap() {
    return CreatePaymentResponse.attributeTypeMap;
  }

  public constructor() {}
}
