/**
 * Commerce Platform API
 * RESTful API for the creation of Commerce Cases with Checkouts and the execution of Payments.
 *
 * OpenAPI spec version: 1.8.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Object containing information about the device of the end customer.
 */
export class CustomerDevice {
  /**
   * The IP address of the customer client from the HTTP Headers.
   */
  'ipAddress'?: string;
  /**
   * Tokenized representation of the end customers device. For example used for PAYONE Buy Now, Pay Later (BNPL).
   */
  'deviceToken'?: string;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
    {
      name: 'ipAddress',
      baseName: 'ipAddress',
      type: 'string',
      format: '',
    },
    {
      name: 'deviceToken',
      baseName: 'deviceToken',
      type: 'string',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return CustomerDevice.attributeTypeMap;
  }

  public constructor() {}
}
