/**
 * Commerce Platform API
 * RESTful API for the creation of Commerce Cases with Checkouts and the execution of Payments.
 *
 * OpenAPI spec version: 1.8.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CapturePaymentResponse } from '../models/CapturePaymentResponse';
import { ShoppingCartResult } from '../models/ShoppingCartResult';

export class DeliverResponse {
  'capturePaymentResponse'?: CapturePaymentResponse;
  'shoppingCart'?: ShoppingCartResult;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
    {
      name: 'capturePaymentResponse',
      baseName: 'capturePaymentResponse',
      type: 'CapturePaymentResponse',
      format: '',
    },
    {
      name: 'shoppingCart',
      baseName: 'shoppingCart',
      type: 'ShoppingCartResult',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return DeliverResponse.attributeTypeMap;
  }

  public constructor() {}
}
