/**
 * Commerce Platform API
 * RESTful API for the creation of Commerce Cases with Checkouts and the execution of Payments.
 *
 * OpenAPI spec version: 1.8.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CancellationReason } from '../models/CancellationReason';
import { DeliverItem } from '../models/DeliverItem';
import { DeliverType } from '../models/DeliverType';

/**
 * Request to mark items of the respective Checkout as delivered and to automatically execute a Capture.  A Deliver can be created for a full or the partial ShoppingCart of the Checkout.  The platform will automatically calculate the respective amount to trigger the Capture. For a partial Deliver a list of items must be provided. The item details for the Capture will be automatically loaded from the Checkout.     The cancellationReason must be provided if deliverType is set to PARTIAL and isFinal is set to true for BNPL payment methods (paymentProductId 3390, 3391 and 3392). For other payment methods the cancellationReason is not mandatory in this case but can be used for reporting and reconciliation purposes.
 */
export class DeliverRequest {
  'deliverType'?: DeliverType;
  /**
   * This property indicates whether this will be the final operation. For deliverType FULL, it is always the final operation. If deliverType PARTIAL is provided and the property is set to true, the remaining amount of the items will be cancelled and the items are marked as CANCELLED.
   */
  'isFinal'?: boolean;
  'cancellationReason'?: CancellationReason;
  'deliverItems'?: Array<DeliverItem>;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
    {
      name: 'deliverType',
      baseName: 'deliverType',
      type: 'DeliverType',
      format: '',
    },
    {
      name: 'isFinal',
      baseName: 'isFinal',
      type: 'boolean',
      format: '',
    },
    {
      name: 'cancellationReason',
      baseName: 'cancellationReason',
      type: 'CancellationReason',
      format: '',
    },
    {
      name: 'deliverItems',
      baseName: 'deliverItems',
      type: 'Array<DeliverItem>',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return DeliverRequest.attributeTypeMap;
  }

  public constructor() {}
}
