/**
 * Commerce Platform API
 * RESTful API for the creation of Commerce Cases with Checkouts and the execution of Payments.
 *
 * OpenAPI spec version: 1.8.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { APIError } from './APIError.js';

export class ErrorResponse {
  /**
   * Unique reference of this error response for debugging purposes
   */
  'errorId'?: string;
  'errors'?: Array<APIError>;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
    {
      name: 'errorId',
      baseName: 'errorId',
      type: 'string',
      format: '',
    },
    {
      name: 'errors',
      baseName: 'errors',
      type: 'Array<APIError>',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return ErrorResponse.attributeTypeMap;
  }

  public constructor() {}
}
