/**
 * Commerce Platform API
 * RESTful API for the creation of Commerce Cases with Checkouts and the execution of Payments.
 *
 * OpenAPI spec version: 1.8.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { APIError } from './APIError.js';

export class ErrorResponse {
  /**
   * Unique reference of this error response for debugging purposes
   */
  errorId: string | null;
  errors: Array<APIError> | null;

  public constructor() {
    this.errorId = null;
    this.errors = null;
  }
}
