/**
 * Commerce Platform API
 * RESTful API for the creation of Commerce Cases with Checkouts and the execution of Payments.
 *
 * OpenAPI spec version: 1.8.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PaymentProduct3392SpecificInput } from '../models/PaymentProduct3392SpecificInput';

/**
 * Object containing the specific input details for financing payment methods (Buy Now Pay Later)
 */
export class FinancingPaymentMethodSpecificInput {
  /**
   * Payment product identifier - please check product documentation for a full overview of possible values. Currently supported payment methods * 3390 - PAYONE Secured Invoice * 3391 - PAYONE Secured Installment * 3392 - PAYONE Secured Direct Debit
   */
  'paymentProductId'?: number;
  /**
   * * true = the payment requires approval before the funds will be captured using the Approve payment or Capture payment API * false = the payment does not require approval, and the funds will be captured automatically  If the parameter is not provided in the request, the default value will be true
   */
  'requiresApproval'?: boolean;
  'paymentProduct3392SpecificInput'?: PaymentProduct3392SpecificInput;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
    {
      name: 'paymentProductId',
      baseName: 'paymentProductId',
      type: 'number',
      format: 'int32',
    },
    {
      name: 'requiresApproval',
      baseName: 'requiresApproval',
      type: 'boolean',
      format: '',
    },
    {
      name: 'paymentProduct3392SpecificInput',
      baseName: 'paymentProduct3392SpecificInput',
      type: 'PaymentProduct3392SpecificInput',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return FinancingPaymentMethodSpecificInput.attributeTypeMap;
  }

  public constructor() {}
}
