/**
 * Commerce Platform API
 * RESTful API for the creation of Commerce Cases with Checkouts and the execution of Payments.
 *
 * OpenAPI spec version: 1.8.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AmountOfMoney } from './AmountOfMoney.js';
import { LinkInformation } from './LinkInformation.js';

export class InstallmentOption {
  /**
   * Installment option Identifier. Use this in the Complete Payment for the selected installment option.
   */
  'installmentOptionId': string;
  /**
   * The number of monthly payments for this installment.
   */
  'numberOfPayments': number;
  /**
   * Monthly rate amount.
   */
  'monthlyAmount': AmountOfMoney;
  /**
   * Last rate amount.
   */
  'lastRateAmount': AmountOfMoney;
  /**
   * Effective interest amount in percent with two decimals.
   */
  'effectiveInterestRate': number;
  /**
   * Nominal interest amount in percent with two decimals.
   */
  'nominalInterestRate': number;
  /**
   * Total rate amount.
   */
  'totalAmount': AmountOfMoney;
  /**
   * Due date of first rate. Format: YYYYMMDD
   */
  'firstRateDate': string;
  /**
   * Link with credit information.
   */
  'creditInformation': LinkInformation;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
    {
      name: 'installmentOptionId',
      baseName: 'installmentOptionId',
      type: 'string',
      format: '',
    },
    {
      name: 'numberOfPayments',
      baseName: 'numberOfPayments',
      type: 'number',
      format: 'int32',
    },
    {
      name: 'monthlyAmount',
      baseName: 'monthlyAmount',
      type: 'AmountOfMoney',
      format: '',
    },
    {
      name: 'lastRateAmount',
      baseName: 'lastRateAmount',
      type: 'AmountOfMoney',
      format: '',
    },
    {
      name: 'effectiveInterestRate',
      baseName: 'effectiveInterestRate',
      type: 'number',
      format: 'int32',
    },
    {
      name: 'nominalInterestRate',
      baseName: 'nominalInterestRate',
      type: 'number',
      format: 'int32',
    },
    {
      name: 'totalAmount',
      baseName: 'totalAmount',
      type: 'AmountOfMoney',
      format: '',
    },
    {
      name: 'firstRateDate',
      baseName: 'firstRateDate',
      type: 'string',
      format: '',
    },
    {
      name: 'creditInformation',
      baseName: 'creditInformation',
      type: 'LinkInformation',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return InstallmentOption.attributeTypeMap;
  }

  public constructor() {}
}
