/**
 * Commerce Platform API
 * RESTful API for the creation of Commerce Cases with Checkouts and the execution of Payments.
 *
 * OpenAPI spec version: 1.8.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * URL and content type information for an web resource.
 */
export class LinkInformation {
  /**
   * URL of link.
   */
  'href': string;
  /**
   * Content type of linked data.
   */
  'type': string;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
    {
      name: 'href',
      baseName: 'href',
      type: 'string',
      format: '',
    },
    {
      name: 'type',
      baseName: 'type',
      type: 'string',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return LinkInformation.attributeTypeMap;
  }

  public constructor() {}
}
