/**
 * Commerce Platform API
 * RESTful API for the creation of Commerce Cases with Checkouts and the execution of Payments.
 *
 * OpenAPI spec version: 1.8.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Specifies whether the mandate is for one-off or recurring payments. Possible values are: * UNIQUE * RECURRING
 */
export enum MandateRecurrenceType {
  Unique = 'UNIQUE',
  Recurring = 'RECURRING',
}
