/**
 * Commerce Platform API
 * RESTful API for the creation of Commerce Cases with Checkouts and the execution of Payments.
 *
 * OpenAPI spec version: 1.8.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AmountOfMoney } from './AmountOfMoney.js';
import { Customer } from './Customer.js';
import { References } from './References.js';
import { Shipping } from './Shipping.js';
import { ShoppingCartInput } from './ShoppingCartInput.js';

/**
 * Order object containing order related data Please note that this object is required to be able to submit the amount.
 */
export class Order {
  'amountOfMoney'?: AmountOfMoney;
  'customer'?: Customer;
  'references': References;
  'shipping'?: Shipping;
  'shoppingCart'?: ShoppingCartInput;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
    {
      name: 'amountOfMoney',
      baseName: 'amountOfMoney',
      type: 'AmountOfMoney',
      format: '',
    },
    {
      name: 'customer',
      baseName: 'customer',
      type: 'Customer',
      format: '',
    },
    {
      name: 'references',
      baseName: 'references',
      type: 'References',
      format: '',
    },
    {
      name: 'shipping',
      baseName: 'shipping',
      type: 'Shipping',
      format: '',
    },
    {
      name: 'shoppingCart',
      baseName: 'shoppingCart',
      type: 'ShoppingCartInput',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return Order.attributeTypeMap;
  }

  public constructor() {}
}
