/**
 * Commerce Platform API
 * RESTful API for the creation of Commerce Cases with Checkouts and the execution of Payments.
 *
 * OpenAPI spec version: 1.8.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { CreatePaymentResponse } from './CreatePaymentResponse.js';
import type { ShoppingCartResult } from './ShoppingCartResult.js';

/** @description Object that contains details on the created payment in case one has been created. */
export interface OrderResponse {
  createPaymentResponse?: CreatePaymentResponse;
  shoppingCart?: ShoppingCartResult;
}
