/**
 * Commerce Platform API
 * RESTful API for the creation of Commerce Cases with Checkouts and the execution of Payments.
 *
 * OpenAPI spec version: 1.8.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CreatePaymentResponse } from '../models/CreatePaymentResponse';
import { ShoppingCartResult } from '../models/ShoppingCartResult';

/**
 * Object that contains details on the created payment in case one has been created.
 */
export class OrderResponse {
  'createPaymentResponse'?: CreatePaymentResponse;
  'shoppingCart'?: ShoppingCartResult;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
    {
      name: 'createPaymentResponse',
      baseName: 'createPaymentResponse',
      type: 'CreatePaymentResponse',
      format: '',
    },
    {
      name: 'shoppingCart',
      baseName: 'shoppingCart',
      type: 'ShoppingCartResult',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return OrderResponse.attributeTypeMap;
  }

  public constructor() {}
}
