/**
 * Commerce Platform API
 * RESTful API for the creation of Commerce Cases with Checkouts and the execution of Payments.
 *
 * OpenAPI spec version: 1.8.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Defines the respective payment type.
 */
export enum PaymentType {
  Sale = 'SALE',
  Reservation = 'RESERVATION',
  Capture = 'CAPTURE',
  Refund = 'REFUND',
  Reversal = 'REVERSAL',
  ChargebackReversal = 'CHARGEBACK_REVERSAL',
  CreditNote = 'CREDIT_NOTE',
  DebitNote = 'DEBIT_NOTE',
}
