/**
 * Commerce Platform API
 * RESTful API for the creation of Commerce Cases with Checkouts and the execution of Payments.
 *
 * OpenAPI spec version: 1.8.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BankAccountInformation } from '../models/BankAccountInformation';

/**
 * Object containing specific information for PAYONE Secured Installment.
 */
export class PaymentProduct3391SpecificInput {
  /**
   * ID of the selected installment option. Will be provided in the response of the Order / Payment Execution request.
   */
  'installmentOptionId': string;
  'bankAccountInformation': BankAccountInformation;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
    {
      name: 'installmentOptionId',
      baseName: 'installmentOptionId',
      type: 'string',
      format: '',
    },
    {
      name: 'bankAccountInformation',
      baseName: 'bankAccountInformation',
      type: 'BankAccountInformation',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return PaymentProduct3391SpecificInput.attributeTypeMap;
  }

  public constructor() {}
}
