/**
 * Commerce Platform API
 * RESTful API for the creation of Commerce Cases with Checkouts and the execution of Payments.
 *
 * OpenAPI spec version: 1.8.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PaymentOutput } from './PaymentOutput.js';
import { PaymentStatusOutput } from './PaymentStatusOutput.js';
import { StatusValue } from './StatusValue.js';

/**
 * Object that holds the payment related properties.
 */
export class PaymentResponse {
  'paymentOutput'?: PaymentOutput;
  'status'?: StatusValue;
  'statusOutput'?: PaymentStatusOutput;
  /**
   * Unique payment transaction identifier of the payment gateway.
   */
  'id'?: string;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
    {
      name: 'paymentOutput',
      baseName: 'paymentOutput',
      type: 'PaymentOutput',
      format: '',
    },
    {
      name: 'status',
      baseName: 'status',
      type: 'StatusValue',
      format: '',
    },
    {
      name: 'statusOutput',
      baseName: 'statusOutput',
      type: 'PaymentStatusOutput',
      format: '',
    },
    {
      name: 'id',
      baseName: 'id',
      type: 'string',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return PaymentResponse.attributeTypeMap;
  }

  public constructor() {}
}
