/**
 * Commerce Platform API
 * RESTful API for the creation of Commerce Cases with Checkouts and the execution of Payments.
 *
 * OpenAPI spec version: 1.8.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { InstallmentOption } from '../models/InstallmentOption';

/**
 * Object containing specific information for PAYONE Secured Installment.
 */
export class PaymentProduct3391SpecificOutput {
  /**
   * List of installment options.
   */
  'installmentOptions'?: Array<InstallmentOption>;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
    {
      name: 'installmentOptions',
      baseName: 'installmentOptions',
      type: 'Array<InstallmentOption>',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return PaymentProduct3391SpecificOutput.attributeTypeMap;
  }

  public constructor() {}
}
