/**
 * Commerce Platform API
 * RESTful API for the creation of Commerce Cases with Checkouts and the execution of Payments.
 *
 * OpenAPI spec version: 1.8.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Output that is SEPA Direct Debit specific (i.e. the used mandate).
 */
export class PaymentProduct771SpecificOutput {
  /**
   * Unique reference fo a SEPA Mandate
   */
  'mandateReference'?: string;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
    {
      name: 'mandateReference',
      baseName: 'mandateReference',
      type: 'string',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return PaymentProduct771SpecificOutput.attributeTypeMap;
  }

  public constructor() {}
}
