/**
 * Commerce Platform API
 * RESTful API for the creation of Commerce Cases with Checkouts and the execution of Payments.
 *
 * OpenAPI spec version: 1.8.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Object containing the details of the PayPal account.
 */
export class PaymentProduct840CustomerAccount {
  /**
   * Name of the company in case the PayPal account is owned by a business
   */
  'companyName'?: string;
  /**
   * First name of the PayPal account holder
   */
  'firstName'?: string;
  /**
   * The unique identifier of a PayPal account and will never change in the life cycle of a PayPal account.
   */
  'payerId'?: string;
  /**
   * Surname of the PayPal account holder
   */
  'surname'?: string;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
    {
      name: 'companyName',
      baseName: 'companyName',
      type: 'string',
      format: '',
    },
    {
      name: 'firstName',
      baseName: 'firstName',
      type: 'string',
      format: '',
    },
    {
      name: 'payerId',
      baseName: 'payerId',
      type: 'string',
      format: '',
    },
    {
      name: 'surname',
      baseName: 'surname',
      type: 'string',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return PaymentProduct840CustomerAccount.attributeTypeMap;
  }

  public constructor() {}
}
