/**
 * Commerce Platform API
 * RESTful API for the creation of Commerce Cases with Checkouts and the execution of Payments.
 *
 * OpenAPI spec version: 1.8.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CardPaymentDetails } from './CardPaymentDetails.js';
import { PaymentChannel } from './PaymentChannel.js';
import { PaymentEvent } from './PaymentEvent.js';

/**
 * Object containing the related data of the created Payment Information.
 */
export class PaymentInformationResponse {
  /**
   * Unique ID of the Commerce Case.
   */
  'commerceCaseId'?: string;
  /**
   * Unique ID of the Commerce Case.
   */
  'checkoutId'?: string;
  /**
   * Unique identifier of the customer.
   */
  'merchantCustomerId'?: string;
  /**
   * Unique ID of the Payment Information.
   */
  'paymentInformationId'?: string;
  'paymentChannel'?: PaymentChannel;
  /**
   * Payment product identifier - please check see product documentation for a full overview of possible values.
   */
  'paymentProductId'?: number;
  /**
   * Unique identifier of the POS terminal of the payment transaction.
   */
  'terminalId'?: string;
  /**
   * Unique ID that identifies a store location or transaction point and which refers to the contract number of the merchant accepting the card.
   */
  'cardAcceptorId'?: string;
  /**
   * Unique reference of the PaymentInformation. In case of card present transactions, the reference from the ECR or terminal will be used. It is always the reference for external transactions. (e.g. card present payments, cash payments or payments processed by other payment providers).
   */
  'merchantReference'?: string;
  'cardPaymentDetails'?: CardPaymentDetails;
  'events'?: Array<PaymentEvent>;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
    {
      name: 'commerceCaseId',
      baseName: 'commerceCaseId',
      type: 'string',
      format: 'UUID',
    },
    {
      name: 'checkoutId',
      baseName: 'checkoutId',
      type: 'string',
      format: 'UUID',
    },
    {
      name: 'merchantCustomerId',
      baseName: 'merchantCustomerId',
      type: 'string',
      format: '',
    },
    {
      name: 'paymentInformationId',
      baseName: 'paymentInformationId',
      type: 'string',
      format: 'UUID',
    },
    {
      name: 'paymentChannel',
      baseName: 'paymentChannel',
      type: 'PaymentChannel',
      format: '',
    },
    {
      name: 'paymentProductId',
      baseName: 'paymentProductId',
      type: 'number',
      format: 'int32',
    },
    {
      name: 'terminalId',
      baseName: 'terminalId',
      type: 'string',
      format: '',
    },
    {
      name: 'cardAcceptorId',
      baseName: 'cardAcceptorId',
      type: 'string',
      format: '',
    },
    {
      name: 'merchantReference',
      baseName: 'merchantReference',
      type: 'string',
      format: '',
    },
    {
      name: 'cardPaymentDetails',
      baseName: 'cardPaymentDetails',
      type: 'CardPaymentDetails',
      format: '',
    },
    {
      name: 'events',
      baseName: 'events',
      type: 'Array<PaymentEvent>',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return PaymentInformationResponse.attributeTypeMap;
  }

  public constructor() {}
}
