/**
 * Commerce Platform API
 * RESTful API for the creation of Commerce Cases with Checkouts and the execution of Payments.
 *
 * OpenAPI spec version: 1.8.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AmountOfMoney } from './AmountOfMoney.js';
import { CardPaymentMethodSpecificOutput } from './CardPaymentMethodSpecificOutput.js';
import { FinancingPaymentMethodSpecificOutput } from './FinancingPaymentMethodSpecificOutput.js';
import { MobilePaymentMethodSpecificOutput } from './MobilePaymentMethodSpecificOutput.js';
import { PaymentReferences } from './PaymentReferences.js';
import { RedirectPaymentMethodSpecificOutput } from './RedirectPaymentMethodSpecificOutput.js';
import { SepaDirectDebitPaymentMethodSpecificOutput } from './SepaDirectDebitPaymentMethodSpecificOutput.js';

/**
 * Object containing payment details.
 */
export class PaymentOutput {
  'amountOfMoney'?: AmountOfMoney;
  /**
   * It allows you to store additional parameters for the transaction in JSON format. This field should not contain any personal data.
   */
  'merchantParameters'?: string;
  'references'?: PaymentReferences;
  'cardPaymentMethodSpecificOutput'?: CardPaymentMethodSpecificOutput;
  'mobilePaymentMethodSpecificOutput'?: MobilePaymentMethodSpecificOutput;
  /**
   * Payment method identifier based on the paymentProductId.
   */
  'paymentMethod'?: string;
  'redirectPaymentMethodSpecificOutput'?: RedirectPaymentMethodSpecificOutput;
  'sepaDirectDebitPaymentMethodSpecificOutput'?: SepaDirectDebitPaymentMethodSpecificOutput;
  'financingPaymentMethodSpecificOutput'?: FinancingPaymentMethodSpecificOutput;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
    {
      name: 'amountOfMoney',
      baseName: 'amountOfMoney',
      type: 'AmountOfMoney',
      format: '',
    },
    {
      name: 'merchantParameters',
      baseName: 'merchantParameters',
      type: 'string',
      format: '',
    },
    {
      name: 'references',
      baseName: 'references',
      type: 'PaymentReferences',
      format: '',
    },
    {
      name: 'cardPaymentMethodSpecificOutput',
      baseName: 'cardPaymentMethodSpecificOutput',
      type: 'CardPaymentMethodSpecificOutput',
      format: '',
    },
    {
      name: 'mobilePaymentMethodSpecificOutput',
      baseName: 'mobilePaymentMethodSpecificOutput',
      type: 'MobilePaymentMethodSpecificOutput',
      format: '',
    },
    {
      name: 'paymentMethod',
      baseName: 'paymentMethod',
      type: 'string',
      format: '',
    },
    {
      name: 'redirectPaymentMethodSpecificOutput',
      baseName: 'redirectPaymentMethodSpecificOutput',
      type: 'RedirectPaymentMethodSpecificOutput',
      format: '',
    },
    {
      name: 'sepaDirectDebitPaymentMethodSpecificOutput',
      baseName: 'sepaDirectDebitPaymentMethodSpecificOutput',
      type: 'SepaDirectDebitPaymentMethodSpecificOutput',
      format: '',
    },
    {
      name: 'financingPaymentMethodSpecificOutput',
      baseName: 'financingPaymentMethodSpecificOutput',
      type: 'FinancingPaymentMethodSpecificOutput',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return PaymentOutput.attributeTypeMap;
  }

  public constructor() {}
}
