/**
 * Commerce Platform API
 * RESTful API for the creation of Commerce Cases with Checkouts and the execution of Payments.
 *
 * OpenAPI spec version: 1.8.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CardPaymentMethodSpecificInput } from '../models/CardPaymentMethodSpecificInput';
import { CustomerDevice } from '../models/CustomerDevice';
import { FinancingPaymentMethodSpecificInput } from '../models/FinancingPaymentMethodSpecificInput';
import { MobilePaymentMethodSpecificInput } from '../models/MobilePaymentMethodSpecificInput';
import { PaymentChannel } from '../models/PaymentChannel';
import { RedirectPaymentMethodSpecificInput } from '../models/RedirectPaymentMethodSpecificInput';
import { SepaDirectDebitPaymentMethodSpecificInput } from '../models/SepaDirectDebitPaymentMethodSpecificInput';

/**
 * Input for the payment for a respective payment method. In case the paymentMethodSpecificInput has already been provided when creating the Commerce Case or Checkout, it will automatically be used for the Payment Execution. If a new input will be provided, the existing input will be updated.
 */
export class PaymentMethodSpecificInput {
  'cardPaymentMethodSpecificInput'?: CardPaymentMethodSpecificInput;
  'mobilePaymentMethodSpecificInput'?: MobilePaymentMethodSpecificInput;
  'redirectPaymentMethodSpecificInput'?: RedirectPaymentMethodSpecificInput;
  'sepaDirectDebitPaymentMethodSpecificInput'?: SepaDirectDebitPaymentMethodSpecificInput;
  'financingPaymentMethodSpecificInput'?: FinancingPaymentMethodSpecificInput;
  'customerDevice'?: CustomerDevice;
  'paymentChannel'?: PaymentChannel;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
    {
      name: 'cardPaymentMethodSpecificInput',
      baseName: 'cardPaymentMethodSpecificInput',
      type: 'CardPaymentMethodSpecificInput',
      format: '',
    },
    {
      name: 'mobilePaymentMethodSpecificInput',
      baseName: 'mobilePaymentMethodSpecificInput',
      type: 'MobilePaymentMethodSpecificInput',
      format: '',
    },
    {
      name: 'redirectPaymentMethodSpecificInput',
      baseName: 'redirectPaymentMethodSpecificInput',
      type: 'RedirectPaymentMethodSpecificInput',
      format: '',
    },
    {
      name: 'sepaDirectDebitPaymentMethodSpecificInput',
      baseName: 'sepaDirectDebitPaymentMethodSpecificInput',
      type: 'SepaDirectDebitPaymentMethodSpecificInput',
      format: '',
    },
    {
      name: 'financingPaymentMethodSpecificInput',
      baseName: 'financingPaymentMethodSpecificInput',
      type: 'FinancingPaymentMethodSpecificInput',
      format: '',
    },
    {
      name: 'customerDevice',
      baseName: 'customerDevice',
      type: 'CustomerDevice',
      format: '',
    },
    {
      name: 'paymentChannel',
      baseName: 'paymentChannel',
      type: 'PaymentChannel',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return PaymentMethodSpecificInput.attributeTypeMap;
  }

  public constructor() {}
}
