/**
 * Commerce Platform API
 * RESTful API for the creation of Commerce Cases with Checkouts and the execution of Payments.
 *
 * OpenAPI spec version: 1.8.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { StatusCategoryValue } from '../models/StatusCategoryValue';

/**
 * This object has the numeric representation of the current payment status, timestamp of last status change and performable action on the current payment resource. In case of failed payments and negative scenarios, detailed error information is listed.
 */
export class PaymentStatusOutput {
  /**
   * Flag indicating if the payment can be cancelled
   */
  'isCancellable'?: boolean;
  'statusCategory'?: StatusCategoryValue;
  /**
   * Indicates if the transaction has been authorized
   */
  'isAuthorized'?: boolean;
  /**
   * Flag indicating if the payment can be refunded
   */
  'isRefundable'?: boolean;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
    {
      name: 'isCancellable',
      baseName: 'isCancellable',
      type: 'boolean',
      format: '',
    },
    {
      name: 'statusCategory',
      baseName: 'statusCategory',
      type: 'StatusCategoryValue',
      format: '',
    },
    {
      name: 'isAuthorized',
      baseName: 'isAuthorized',
      type: 'boolean',
      format: '',
    },
    {
      name: 'isRefundable',
      baseName: 'isRefundable',
      type: 'boolean',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return PaymentStatusOutput.attributeTypeMap;
  }

  public constructor() {}
}
