/**
 * Commerce Platform API
 * RESTful API for the creation of Commerce Cases with Checkouts and the execution of Payments.
 *
 * OpenAPI spec version: 1.8.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BankAccountInformation } from './BankAccountInformation.js';

/**
 * Object containing specific information for PAYONE Secured Direct. Debit.
 */
export class PaymentProduct3392SpecificInput {
  'bankAccountInformation': BankAccountInformation;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
    {
      name: 'bankAccountInformation',
      baseName: 'bankAccountInformation',
      type: 'BankAccountInformation',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return PaymentProduct3392SpecificInput.attributeTypeMap;
  }

  public constructor() {}
}
