/**
 * Commerce Platform API
 * RESTful API for the creation of Commerce Cases with Checkouts and the execution of Payments.
 *
 * OpenAPI spec version: 1.8.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ApplePaymentDataTokenInformation } from './ApplePaymentDataTokenInformation.js';

/**
 * Object containing additional Information needed for Apple Pay payment transactions.
 */
export class PaymentProduct320SpecificInput {
  'network'?: PaymentProduct320SpecificInputNetworkEnum;
  'token'?: ApplePaymentDataTokenInformation;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
    {
      name: 'network',
      baseName: 'network',
      type: 'PaymentProduct320SpecificInputNetworkEnum',
      format: '',
    },
    {
      name: 'token',
      baseName: 'token',
      type: 'ApplePaymentDataTokenInformation',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return PaymentProduct320SpecificInput.attributeTypeMap;
  }

  public constructor() {}
}

export enum PaymentProduct320SpecificInputNetworkEnum {
  Mastercard = 'MASTERCARD',
  Visa = 'VISA',
  Amex = 'AMEX',
  Girocard = 'GIROCARD',
  Discover = 'DISCOVER',
  Jcb = 'JCB',
}
