/**
 * Commerce Platform API
 * RESTful API for the creation of Commerce Cases with Checkouts and the execution of Payments.
 *
 * OpenAPI spec version: 1.8.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PaymentExecutionSpecificInput } from '../models/PaymentExecutionSpecificInput';
import { PaymentMethodSpecificInput } from '../models/PaymentMethodSpecificInput';

/**
 * Request to trigger a payment for a respective Checkout providing the input for a specific payment method.  The data from the Commerce case and the Checkout will not be loaded automatically and there is no validation between the data input in place.  Depending on the payment method, information of the customer and / or the shopping cart might be required.  For more details regarding payment method specific input please check the documentation.
 */
export class PaymentExecutionRequest {
  'paymentMethodSpecificInput'?: PaymentMethodSpecificInput;
  'paymentExecutionSpecificInput'?: PaymentExecutionSpecificInput;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
    {
      name: 'paymentMethodSpecificInput',
      baseName: 'paymentMethodSpecificInput',
      type: 'PaymentMethodSpecificInput',
      format: '',
    },
    {
      name: 'paymentExecutionSpecificInput',
      baseName: 'paymentExecutionSpecificInput',
      type: 'PaymentExecutionSpecificInput',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return PaymentExecutionRequest.attributeTypeMap;
  }

  public constructor() {}
}
