/**
 * Commerce Platform API
 * RESTful API for the creation of Commerce Cases with Checkouts and the execution of Payments.
 *
 * OpenAPI spec version: 1.8.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AmountOfMoney } from '../models/AmountOfMoney';
import { PaymentReferences } from '../models/PaymentReferences';

/**
 * Object containing details from the created payout.
 */
export class PayoutOutput {
  'amountOfMoney'?: AmountOfMoney;
  'references'?: PaymentReferences;
  /**
   * Payment method identifier based on the paymentProductId.
   */
  'paymentMethod'?: string;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
    {
      name: 'amountOfMoney',
      baseName: 'amountOfMoney',
      type: 'AmountOfMoney',
      format: '',
    },
    {
      name: 'references',
      baseName: 'references',
      type: 'PaymentReferences',
      format: '',
    },
    {
      name: 'paymentMethod',
      baseName: 'paymentMethod',
      type: 'string',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return PayoutOutput.attributeTypeMap;
  }

  public constructor() {}
}
