/**
 * Commerce Platform API
 * RESTful API for the creation of Commerce Cases with Checkouts and the execution of Payments.
 *
 * OpenAPI spec version: 1.8.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PersonalName } from '../models/PersonalName';

/**
 * Object containing personal information like name, date of birth and gender.
 */
export class PersonalInformation {
  /**
   * The date of birth of the customer of the recipient of the loan. Format YYYYMMDD
   */
  'dateOfBirth'?: string;
  /**
   * The gender of the customer, possible values are:  * MALE  * FEMALE  * UNKNOWN
   */
  'gender'?: PersonalInformationGenderEnum;
  'name'?: PersonalName;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
    {
      name: 'dateOfBirth',
      baseName: 'dateOfBirth',
      type: 'string',
      format: '',
    },
    {
      name: 'gender',
      baseName: 'gender',
      type: 'PersonalInformationGenderEnum',
      format: '',
    },
    {
      name: 'name',
      baseName: 'name',
      type: 'PersonalName',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return PersonalInformation.attributeTypeMap;
  }

  public constructor() {}
}

export enum PersonalInformationGenderEnum {
  Male = 'MALE',
  Female = 'FEMALE',
  Unknown = 'UNKNOWN',
}
