/**
 * Commerce Platform API
 * RESTful API for the creation of Commerce Cases with Checkouts and the execution of Payments.
 *
 * OpenAPI spec version: 1.8.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Object containing the name details of the customer
 */
export class PersonalName {
  /**
   * Given name(s) or first name(s) of the customer
   */
  'firstName'?: string;
  /**
   * Surname(s) or last name(s) of the customer
   */
  'surname'?: string;
  /**
   * Title of customer
   */
  'title'?: string;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
    {
      name: 'firstName',
      baseName: 'firstName',
      type: 'string',
      format: '',
    },
    {
      name: 'surname',
      baseName: 'surname',
      type: 'string',
      format: '',
    },
    {
      name: 'title',
      baseName: 'title',
      type: 'string',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return PersonalName.attributeTypeMap;
  }

  public constructor() {}
}
