/**
 * Commerce Platform API
 * RESTful API for the creation of Commerce Cases with Checkouts and the execution of Payments.
 *
 * OpenAPI spec version: 1.8.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Object containing amount and ISO currency code attributes
 */
export class PositiveAmountOfMoney {
  /**
   * Amount in cents and always having 2 decimals
   */
  'amount': number;
  /**
   * Three-letter ISO currency code representing the currency for the amount
   */
  'currencyCode': string;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
    {
      name: 'amount',
      baseName: 'amount',
      type: 'number',
      format: 'int64',
    },
    {
      name: 'currencyCode',
      baseName: 'currencyCode',
      type: 'string',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return PositiveAmountOfMoney.attributeTypeMap;
  }

  public constructor() {}
}
