/**
 * Commerce Platform API
 * RESTful API for the creation of Commerce Cases with Checkouts and the execution of Payments.
 *
 * OpenAPI spec version: 1.8.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BankAccountInformation } from '../models/BankAccountInformation';
import { MandateRecurrenceType } from '../models/MandateRecurrenceType';

/**
 * Object containing the relevant information of a SEPA Direct Debit mandate for processing (mandatory fields in pain.008). Renamed from CreateMandateWithReturnUrl to ProcessingMandateInformation.
 */
export class ProcessingMandateInformation {
  'bankAccountIban': BankAccountInformation;
  'recurrenceType': MandateRecurrenceType;
  /**
   * The unique identifier of the mandate
   */
  'uniqueMandateReference': string;
  /**
   * The date of signature of the mandate. Format YYYYMMDD
   */
  'dateOfSignature': string;
  /**
   * Your unique creditor identifier.
   */
  'creditorId': string;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
    {
      name: 'bankAccountIban',
      baseName: 'bankAccountIban',
      type: 'BankAccountInformation',
      format: '',
    },
    {
      name: 'recurrenceType',
      baseName: 'recurrenceType',
      type: 'MandateRecurrenceType',
      format: '',
    },
    {
      name: 'uniqueMandateReference',
      baseName: 'uniqueMandateReference',
      type: 'string',
      format: '',
    },
    {
      name: 'dateOfSignature',
      baseName: 'dateOfSignature',
      type: 'string',
      format: '',
    },
    {
      name: 'creditorId',
      baseName: 'creditorId',
      type: 'string',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return ProcessingMandateInformation.attributeTypeMap;
  }

  public constructor() {}
}
