/**
 * Commerce Platform API
 * RESTful API for the creation of Commerce Cases with Checkouts and the execution of Payments.
 *
 * OpenAPI spec version: 1.8.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Enum to classify items that are purchased * GOODS - Goods * SHIPMENT - Shipping charges * HANDLING_FEE - Handling fee * DISCOUNT - Voucher / discount
 */
export enum ProductType {
  Goods = 'GOODS',
  Shipment = 'SHIPMENT',
  HandlingFee = 'HANDLING_FEE',
  Discount = 'DISCOUNT',
}
