/**
 * Commerce Platform API
 * RESTful API for the creation of Commerce Cases with Checkouts and the execution of Payments.
 *
 * OpenAPI spec version: 1.8.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Object containing all data needed to redirect the customer.
 */
export class RedirectData {
  /**
   * The URL that the customer should be redirected to. Be sure to redirect using the GET method
   */
  'redirectURL'?: string;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
    {
      name: 'redirectURL',
      baseName: 'redirectURL',
      type: 'string',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return RedirectData.attributeTypeMap;
  }

  public constructor() {}
}
