/**
 * Commerce Platform API
 * RESTful API for the creation of Commerce Cases with Checkouts and the execution of Payments.
 *
 * OpenAPI spec version: 1.8.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Object containing specific input required for PayPal payments (Payment product ID 840)
 */
export class RedirectPaymentProduct840SpecificInput {
  /**
   * Indicates whether to use PayPal Express Checkout Shortcut.  * true = When shortcut is enabled, the consumer can select a shipping address during PayPal checkout.  * false = When shortcut is disabled, the consumer cannot change the shipping address. Default value is false. Please note that this field is ignored when order.additionalInput.typeInformation.purchaseType is set to \"digital\"
   */
  'addressSelectionAtPayPal'?: boolean;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
    {
      name: 'addressSelectionAtPayPal',
      baseName: 'addressSelectionAtPayPal',
      type: 'boolean',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return RedirectPaymentProduct840SpecificInput.attributeTypeMap;
  }

  public constructor() {}
}
