/**
 * Commerce Platform API
 * RESTful API for the creation of Commerce Cases with Checkouts and the execution of Payments.
 *
 * OpenAPI spec version: 1.8.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RedirectPaymentProduct840SpecificInput } from './RedirectPaymentProduct840SpecificInput.js';
import { RedirectionData } from './RedirectionData.js';

/**
 * Object containing the specific input details for payments that involve redirects to 3rd parties to complete, like iDeal and PayPal
 */
export class RedirectPaymentMethodSpecificInput {
  /**
   * * true = the payment requires approval before the funds will be captured using the Approve payment or Capture payment API * false = the payment does not require approval, and the funds will be captured automatically  If the parameter is not provided in the request, the default value will be true
   */
  'requiresApproval'?: boolean;
  /**
   * ID of the token to use to create the payment.
   */
  'paymentProcessingToken'?: string;
  /**
   * Token to identify the card in the reporting.
   */
  'reportingToken'?: string;
  /**
   * Indicates if this transaction should be tokenized   * true - Tokenize the transaction.   * false - Do not tokenize the transaction, unless it would be tokenized by other means such as auto- tokenization of recurring payments. example: false
   */
  'tokenize'?: boolean;
  /**
   * Payment product identifier - please check product documentation for a full overview of possible values.
   */
  'paymentProductId'?: number;
  'paymentProduct840SpecificInput'?: RedirectPaymentProduct840SpecificInput;
  'redirectionData'?: RedirectionData;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
    {
      name: 'requiresApproval',
      baseName: 'requiresApproval',
      type: 'boolean',
      format: '',
    },
    {
      name: 'paymentProcessingToken',
      baseName: 'paymentProcessingToken',
      type: 'string',
      format: '',
    },
    {
      name: 'reportingToken',
      baseName: 'reportingToken',
      type: 'string',
      format: '',
    },
    {
      name: 'tokenize',
      baseName: 'tokenize',
      type: 'boolean',
      format: '',
    },
    {
      name: 'paymentProductId',
      baseName: 'paymentProductId',
      type: 'number',
      format: 'int32',
    },
    {
      name: 'paymentProduct840SpecificInput',
      baseName: 'paymentProduct840SpecificInput',
      type: 'RedirectPaymentProduct840SpecificInput',
      format: '',
    },
    {
      name: 'redirectionData',
      baseName: 'redirectionData',
      type: 'RedirectionData',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return RedirectPaymentMethodSpecificInput.attributeTypeMap;
  }

  public constructor() {}
}
