/**
 * Commerce Platform API
 * RESTful API for the creation of Commerce Cases with Checkouts and the execution of Payments.
 *
 * OpenAPI spec version: 1.8.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PaymentProduct840SpecificOutput } from '../models/PaymentProduct840SpecificOutput';

/**
 * Object containing the redirect payment product details.
 */
export class RedirectPaymentMethodSpecificOutput {
  /**
   * <- Payment product identifier - please check product documentation for a full overview of possible values.
   */
  'paymentProductId'?: number;
  'paymentProduct840SpecificOutput'?: PaymentProduct840SpecificOutput;
  /**
   * ID of the token. This property is populated when the payment was done with a token.
   */
  'paymentProcessingToken'?: string;
  /**
   * Token to identify the card in the reporting.
   */
  'reportingToken'?: string;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
    {
      name: 'paymentProductId',
      baseName: 'paymentProductId',
      type: 'number',
      format: 'int32',
    },
    {
      name: 'paymentProduct840SpecificOutput',
      baseName: 'paymentProduct840SpecificOutput',
      type: 'PaymentProduct840SpecificOutput',
      format: '',
    },
    {
      name: 'paymentProcessingToken',
      baseName: 'paymentProcessingToken',
      type: 'string',
      format: '',
    },
    {
      name: 'reportingToken',
      baseName: 'reportingToken',
      type: 'string',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return RedirectPaymentMethodSpecificOutput.attributeTypeMap;
  }

  public constructor() {}
}
