/**
 * Commerce Platform API
 * RESTful API for the creation of Commerce Cases with Checkouts and the execution of Payments.
 *
 * OpenAPI spec version: 1.8.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PaymentStatusOutput } from './PaymentStatusOutput.js';
import { RefundOutput } from './RefundOutput.js';
import { StatusValue } from './StatusValue.js';

/**
 * This object has the numeric representation of the current Refund status, timestamp of last status change and performable action on the current Refund resource. In case of a rejected Refund, detailed error information is listed.
 */
export class RefundPaymentResponse {
  'refundOutput'?: RefundOutput;
  'status'?: StatusValue;
  'statusOutput'?: PaymentStatusOutput;
  /**
   * Unique payment transaction identifier of the payment gateway.
   */
  'id'?: string;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
    {
      name: 'refundOutput',
      baseName: 'refundOutput',
      type: 'RefundOutput',
      format: '',
    },
    {
      name: 'status',
      baseName: 'status',
      type: 'StatusValue',
      format: '',
    },
    {
      name: 'statusOutput',
      baseName: 'statusOutput',
      type: 'PaymentStatusOutput',
      format: '',
    },
    {
      name: 'id',
      baseName: 'id',
      type: 'string',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return RefundPaymentResponse.attributeTypeMap;
  }

  public constructor() {}
}
