/**
 * Commerce Platform API
 * RESTful API for the creation of Commerce Cases with Checkouts and the execution of Payments.
 *
 * OpenAPI spec version: 1.8.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PaymentReferences } from './PaymentReferences.js';
import { PositiveAmountOfMoney } from './PositiveAmountOfMoney.js';
import { ReturnInformation } from './ReturnInformation.js';

/**
 * Request to refund a payment for a Checkout. It is possible to perform multiple partial refunds by providing an amount that is lower than the total captured amount. The returnReason can be provided for reporting and reconciliation purposes but is not mandatory.
 */
export class RefundRequest {
  'amountOfMoney'?: PositiveAmountOfMoney;
  'references'?: PaymentReferences;
  '_return'?: ReturnInformation;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
    {
      name: 'amountOfMoney',
      baseName: 'amountOfMoney',
      type: 'PositiveAmountOfMoney',
      format: '',
    },
    {
      name: 'references',
      baseName: 'references',
      type: 'PaymentReferences',
      format: '',
    },
    {
      name: '_return',
      baseName: 'return',
      type: 'ReturnInformation',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return RefundRequest.attributeTypeMap;
  }

  public constructor() {}
}
