/**
 * Commerce Platform API
 * RESTful API for the creation of Commerce Cases with Checkouts and the execution of Payments.
 *
 * OpenAPI spec version: 1.8.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AmountOfMoney } from './AmountOfMoney.js';
import { PaymentReferences } from './PaymentReferences.js';

/**
 * Object containing Refund details
 */
export class RefundOutput {
  'amountOfMoney'?: AmountOfMoney;
  /**
   * It allows you to store additional parameters for the transaction in JSON format. This field must not contain any personal data.
   */
  'merchantParameters'?: string;
  'references'?: PaymentReferences;
  /**
   * Payment method identifier used by the our payment engine.
   */
  'paymentMethod'?: string;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
    {
      name: 'amountOfMoney',
      baseName: 'amountOfMoney',
      type: 'AmountOfMoney',
      format: '',
    },
    {
      name: 'merchantParameters',
      baseName: 'merchantParameters',
      type: 'string',
      format: '',
    },
    {
      name: 'references',
      baseName: 'references',
      type: 'PaymentReferences',
      format: '',
    },
    {
      name: 'paymentMethod',
      baseName: 'paymentMethod',
      type: 'string',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return RefundOutput.attributeTypeMap;
  }

  public constructor() {}
}
