/**
 * Commerce Platform API
 * RESTful API for the creation of Commerce Cases with Checkouts and the execution of Payments.
 *
 * OpenAPI spec version: 1.8.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ReturnItem } from '../models/ReturnItem';
import { ReturnType } from '../models/ReturnType';

/**
 * Request to mark items of the respective Checkout as returned and to automatically refund a payment for those items.  A Return can be created for a full or the partial ShoppingCart of the Checkout.  The platform will automatically calculate the respective amount to trigger the Refund. For a partial Return a list of items must be provided. The item details for the Refund will be automatically loaded from the Checkout.        The returnReason can be provided for reporting and reconciliation purposes but is not mandatory.
 */
export class ReturnRequest {
  'returnType'?: ReturnType;
  /**
   * Reason of the Refund (e.g. communicated by or to the consumer).
   */
  'returnReason'?: string;
  'returnItems'?: Array<ReturnItem>;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
    {
      name: 'returnType',
      baseName: 'returnType',
      type: 'ReturnType',
      format: '',
    },
    {
      name: 'returnReason',
      baseName: 'returnReason',
      type: 'string',
      format: '',
    },
    {
      name: 'returnItems',
      baseName: 'returnItems',
      type: 'Array<ReturnItem>',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return ReturnRequest.attributeTypeMap;
  }

  public constructor() {}
}
