/**
 * Commerce Platform API
 * RESTful API for the creation of Commerce Cases with Checkouts and the execution of Payments.
 *
 * OpenAPI spec version: 1.8.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class ReturnItem {
  /**
   * Id of the item to return.
   */
  'id': string;
  /**
   * Quantity of the units being returned, should be greater than zero Note: Must not be all spaces or all zeros
   */
  'quantity': number;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
    {
      name: 'id',
      baseName: 'id',
      type: 'string',
      format: 'UUID',
    },
    {
      name: 'quantity',
      baseName: 'quantity',
      type: 'number',
      format: 'int64',
    },
  ];

  static getAttributeTypeMap() {
    return ReturnItem.attributeTypeMap;
  }

  public constructor() {}
}
