/**
 * Commerce Platform API
 * RESTful API for the creation of Commerce Cases with Checkouts and the execution of Payments.
 *
 * OpenAPI spec version: 1.8.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SepaDirectDebitPaymentProduct771SpecificInput } from './SepaDirectDebitPaymentProduct771SpecificInput.js';

/**
 * Object containing the specific input details for SEPA direct debit payments
 */
export class SepaDirectDebitPaymentMethodSpecificInput {
  'paymentProduct771SpecificInput'?: SepaDirectDebitPaymentProduct771SpecificInput;
  /**
   * Payment product identifier - please check product documentation for a full overview of possible values.
   */
  'paymentProductId'?: number;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
    {
      name: 'paymentProduct771SpecificInput',
      baseName: 'paymentProduct771SpecificInput',
      type: 'SepaDirectDebitPaymentProduct771SpecificInput',
      format: '',
    },
    {
      name: 'paymentProductId',
      baseName: 'paymentProductId',
      type: 'number',
      format: 'int32',
    },
  ];

  static getAttributeTypeMap() {
    return SepaDirectDebitPaymentMethodSpecificInput.attributeTypeMap;
  }

  public constructor() {}
}
