/**
 * Commerce Platform API
 * RESTful API for the creation of Commerce Cases with Checkouts and the execution of Payments.
 *
 * OpenAPI spec version: 1.8.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ProcessingMandateInformation } from './ProcessingMandateInformation.js';

/**
 * Object containing information specific to SEPA Direct Debit
 */
export class SepaDirectDebitPaymentProduct771SpecificInput {
  /**
   * The unique reference of the existing mandate to use in this payment.
   */
  'existingUniqueMandateReference'?: string;
  'mandate'?: ProcessingMandateInformation;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
    {
      name: 'existingUniqueMandateReference',
      baseName: 'existingUniqueMandateReference',
      type: 'string',
      format: '',
    },
    {
      name: 'mandate',
      baseName: 'mandate',
      type: 'ProcessingMandateInformation',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return SepaDirectDebitPaymentProduct771SpecificInput.attributeTypeMap;
  }

  public constructor() {}
}
