/**
 * Commerce Platform API
 * RESTful API for the creation of Commerce Cases with Checkouts and the execution of Payments.
 *
 * OpenAPI spec version: 1.8.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AddressPersonal } from '../models/AddressPersonal';

/**
 * Object containing information regarding shipping / delivery
 */
export class Shipping {
  'address'?: AddressPersonal;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
    {
      name: 'address',
      baseName: 'address',
      type: 'AddressPersonal',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return Shipping.attributeTypeMap;
  }

  public constructor() {}
}
