/**
 * Commerce Platform API
 * RESTful API for the creation of Commerce Cases with Checkouts and the execution of Payments.
 *
 * OpenAPI spec version: 1.8.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CartItemResult } from './CartItemResult.js';

/**
 * Shopping cart data, including items and specific amounts.
 */
export class ShoppingCartResult {
  'items'?: Array<CartItemResult>;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
    {
      name: 'items',
      baseName: 'items',
      type: 'Array<CartItemResult>',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return ShoppingCartResult.attributeTypeMap;
  }

  public constructor() {}
}
