/**
 * Commerce Platform API
 * RESTful API for the creation of Commerce Cases with Checkouts and the execution of Payments.
 *
 * OpenAPI spec version: 1.8.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Highlevel status of the payment, payout or Refund.
 */
export enum StatusCategoryValue {
  Created = 'CREATED',
  Unsuccessful = 'UNSUCCESSFUL',
  PendingPayment = 'PENDING_PAYMENT',
  PendingMerchant = 'PENDING_MERCHANT',
  PendingConnectOr3RdParty = 'PENDING_CONNECT_OR_3RD_PARTY',
  Completed = 'COMPLETED',
  Reversed = 'REVERSED',
  Refunded = 'REFUNDED',
}
