/**
 * Commerce Platform API
 * RESTful API for the creation of Commerce Cases with Checkouts and the execution of Payments.
 *
 * OpenAPI spec version: 1.8.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Current high-level status of the Checkout
 */
export enum StatusCheckout {
  Open = 'OPEN',
  PendingCompletion = 'PENDING_COMPLETION',
  Completed = 'COMPLETED',
  Billed = 'BILLED',
  Chargebacked = 'CHARGEBACKED',
  Deleted = 'DELETED',
}
