/**
 * Commerce Platform API
 * RESTful API for the creation of Commerce Cases with Checkouts and the execution of Payments.
 *
 * OpenAPI spec version: 1.8.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 3D Secure results object
 */
export class ThreeDSecureResults {
  /**
   * 3D Secure Protocol version used during this transaction.
   */
  'version'?: string;
  /**
   * 3D Secure ECI (Electronic Commerce Indicator) depending on the Scheme. Returned by DS.
   */
  'schemeEci'?: string;
  /**
   * Exemption requested and applied in the authorization.
   */
  'appliedExemption'?: ThreeDSecureResultsAppliedExemptionEnum;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
    {
      name: 'version',
      baseName: 'version',
      type: 'string',
      format: '',
    },
    {
      name: 'schemeEci',
      baseName: 'schemeEci',
      type: 'string',
      format: '',
    },
    {
      name: 'appliedExemption',
      baseName: 'appliedExemption',
      type: 'ThreeDSecureResultsAppliedExemptionEnum',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return ThreeDSecureResults.attributeTypeMap;
  }

  public constructor() {}
}

export enum ThreeDSecureResultsAppliedExemptionEnum {
  LowValue = 'low-value',
  MerchantAcquirerTransactionRiskAnalysis = 'merchant-acquirer-transaction-risk-analysis',
}
