/**
 * Commerce Platform API
 * RESTful API for the creation of Commerce Cases with Checkouts and the execution of Payments.
 *
 * OpenAPI spec version: 1.8.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Indicates the channel via which the payment is created. Allowed values:   * ECOMMERCE - The transaction is a regular E-Commerce transaction.   * MOTO - The transaction is a Mail Order/Telephone Order.    Defaults to ECOMMERCE.
 */
export enum TransactionChannel {
  Ecommerce = 'ECOMMERCE',
  Moto = 'MOTO',
}
